### ISSUE TITLE
DynamoHosts.byName() fails with AmazonServiceException

### ISSUE THREAD

**Issue by darkled** [yegor256/s3auth#237]
Method `com.s3auth.hosts.DynamoHosts.byName(String name)` invocation with `name = "localhost:54909"` causes an exception on `this.dynamo.load()`:
```
com.amazonaws.AmazonServiceException: Status Code: 400, AWS Service: AmazonDynamoDBv2, AWS Request ID: OBBC8EPTOEHLFFVFL8VNA2QSF3VV4KQNSO5AEMVJF66Q9ASUAAJG, AWS Error Code: UnrecognizedClientException, AWS Error Message: The security token included in the request is invalid.
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:798)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:421)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:232)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke(AmazonDynamoDBClient.java:2996)
	at com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.scan(AmazonDynamoDBClient.java:430)
	at com.s3auth.hosts.DefaultDynamo.load_aroundBody2(DefaultDynamo.java:168)
	at com.s3auth.hosts.DefaultDynamo$AjcClosure3.run(DefaultDynamo.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodCacher$Tunnel.through(MethodCacher.java:282)
	at com.jcabi.aspects.aj.MethodCacher.cache(MethodCacher.java:127)
	at com.s3auth.hosts.DefaultDynamo.load(DefaultDynamo.java:166)
	at com.s3auth.hosts.DefaultDynamo.load(DefaultDynamo.java:1)
	at com.s3auth.hosts.DynamoHosts.byName(DynamoHosts.java:181)
	at com.s3auth.hosts.DynamoHosts.find_aroundBody0(DynamoHosts.java:94)
	at com.s3auth.hosts.DynamoHosts$AjcClosure1.run(DynamoHosts.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
	at com.s3auth.hosts.DynamoHosts.find_aroundBody2(DynamoHosts.java:94)
	at com.s3auth.hosts.DynamoHosts$AjcClosure3.run(DynamoHosts.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
	at com.s3auth.hosts.DynamoHosts.find(DynamoHosts.java:94)
	at com.s3auth.relay.HttpThread.host(HttpThread.java:307)
	at com.s3auth.relay.HttpThread.dispatch(HttpThread.java:168)
	at com.s3auth.relay.HttpFacade$HttpThreadRunnable.run(HttpFacade.java:255)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
	at java.lang.Thread.run(Thread.java:745)
```

Does anyone know what could be the reason and where can I take a look in further investigation?

To reproduce it, you need to get commit f35037e504c83662cc371840076e23803c99508e and execute MainTest.

**Comment by darkled** [comment]
@yegor256 it was a question, but it is not relevant anymore. Thanks.
