### ISSUE TITLE
s3auth-relay: Attribute 'S3Auth-AwsDynamoTable' not found in MANIFEST.MF file

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/s3auth#241]
When I ran `mvn clean install -Pqulice` after changing a file in `s3auth-relay` project, I got this error:

```
[INFO] Exception in thread "main" java.lang.IllegalArgumentException: Attribute
'S3Auth-AwsDynamoTable' not found in MANIFEST.MF file(s) among 60 other attribut
e(s): ["Ant-Version", "Archiver-Version", "Bnd-LastModified", "Build-Id", "Build
-Jdk", "Build-Timestamp", "Built-By", "Bundle-Activator", "Bundle-Category", "Bu
ndle-Description", "Bundle-DocURL", "Bundle-License", "Bundle-ManifestVersion",
"Bundle-Name", "Bundle-RequiredExecutionEnvironment", "Bundle-SymbolicName", "Bu
ndle-Vendor", "Bundle-Version", "Created-By", "DynamicImport-Package", "Export-P
ackage", "Extension-Name", "Fragment-Host", "Ignore-Package", "Implementation-Bu
ild", "Implementation-Build-Date", "Implementation-Title", "Implementation-URL",
 "Implementation-Vendor", "Implementation-Vendor-Id", "Implementation-Version",
"Implementation-Version-Detail", "Import-Package", "Include-Resource", "JCabi-Bu
ild", "JCabi-Date", "JCabi-Version", "Java-Vendor", "Java-Version", "Main-Class"
, "Manifest-Version", "Maven-Version", "Originally-Created-By", "Os-Arch", "Os-N
ame", "Os-Version", "Package", "Premain-Class", "Require-Capability", "Scm-Conne
ction", "Scm-Revision", "Scm-Url", "Specification-Title", "Specification-Vendor"
, "Specification-Version", "Time-Zone-Database-Version", "Tool", "X-Compile-Sour
ce-JDK", "X-Compile-Target-JDK", "url"]
[INFO]  at com.jcabi.manifests.Manifests.read(Manifests.java:274)
[INFO]  at com.s3auth.hosts.DefaultDynamo.<init>(DefaultDynamo.java:121)
[INFO]  at com.s3auth.hosts.DynamoHosts.<init>(DynamoHosts.java:73)
[INFO]  at com.s3auth.relay.Main.main_aroundBody0(Main.java:85)
[INFO]  at com.s3auth.relay.Main$AjcClosure1.run(Main.java:1)
[INFO]  at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:
149)
[INFO]  at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
[INFO]  at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_as
pects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1
)
[INFO]  at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
[INFO]  at com.s3auth.relay.Main.main(Main.java:69)
[INFO] [INFO] ------------------------------------------------------------------
------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------
------
[INFO] [INFO] Total time: 16.037 s
[INFO] [INFO] Finished at: 2014-12-28T22:54:25+04:00
[INFO] [INFO] Final Memory: 10M/25M
[INFO] [INFO] ------------------------------------------------------------------
------
[INFO] [WARNING] The requested profile "qulice" could not be activated because i
t does not exist.
[INFO] [ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:
exec (execute-relay-JAR) on project s3auth-relay-non-daemon: Command execution f
ailed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute
 goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (execute-relay-JAR) on proj
ect s3auth-relay-non-daemon: Command execution failed.
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:216)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:153)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:145)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:116)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProje
ct(LifecycleModuleBuilder.java:80)
[INFO]  at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThre
adedBuilder.build(SingleThreadedBuilder.java:51)
[INFO]  at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(Lifecycl
eStarter.java:120)
[INFO]  at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
[INFO]  at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
[INFO]  at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[INFO]  at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
[INFO]  at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO]  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
[INFO]  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
[INFO]  at java.lang.reflect.Method.invoke(Method.java:606)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Laun
cher.java:289)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.jav
a:229)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(La
uncher.java:415)
[INFO]  at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:
356)
[INFO] Caused by: org.apache.maven.plugin.MojoExecutionException: Command execut
ion failed.
[INFO]  at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:362)
[INFO]  at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(Default
BuildPluginManager.java:132)
[INFO]  at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor
.java:208)
[INFO]  ... 19 more
[INFO] Caused by: org.apache.commons.exec.ExecuteException: Process exited with
an error: 1 (Exit value: 1)
[INFO]  at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecut
or.java:377)
[INFO]  at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:
160)
[INFO]  at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:610)

[INFO]  at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:352)
[INFO]  ... 21 more
[INFO] [ERROR]
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR]
[INFO] [ERROR] For more information about the errors and possible solutions, ple
ase read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExe
cutionException
[INFO] ..FAILED (19.0 s)
[INFO]   The build exited with code 1. See D:\dev\teamed.io\s3auth\s3auth-relay\
target\it\non-daemon\build.log for details.
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 0, Failed: 1, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[ERROR] The following builds failed:
[ERROR] *  non-daemon\pom.xml
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] s3auth ............................................. SUCCESS [01:17 min]
[INFO] s3auth-hosts ....................................... SUCCESS [02:34 min]
[INFO] s3auth-relay ....................................... FAILURE [01:57 min]
[INFO] s3auth-rest ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:50 min
[INFO] Finished at: 2014-12-28T22:54:25+04:00
[INFO] Final Memory: 44M/161M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-invoker-plugin:1.9
:run (default) on project s3auth-relay: 1 build failed. See console output above
 for details. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :s3auth-relay
```

The error does not occur, if I don't touch `s3auth-relay` after checkout.

Please fix the error above.

**Comment by yegor256** [comment]
@dpisarenko This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!
