### ISSUE TITLE
IllegalAccessException for stop method in ExtendedTomcat

### ISSUE THREAD

**Issue by simonjenga** [yegor256/s3auth#273]
```./s3auth>mvn clean install -DskipTests -Dinvoker.skip=true -Pqulice```
```
[INFO]
[INFO] --- tomcat7-maven-plugin:2.2:run-war-only (start-tomcat) @ s3auth-rest ---
[INFO] Running war on http://localhost:53685/
[INFO] Creating Tomcat server configuration at C:\javaworkspace\s3auth\s3auth-rest\target\tomcat
[INFO] create webapp with contextPath:
Mar 12, 2015 12:14:29 PM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-bio-53685"]
Mar 12, 2015 12:14:29 PM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Mar 12, 2015 12:14:29 PM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/7.0.47
Mar 12, 2015 12:14:40 PM org.apache.catalina.loader.WebappClassLoader validateJarFile
INFO: validateJarFile(C:\javaworkspace\s3auth\s3auth-rest\target\s3auth-rest\WEB-INF\lib\tomcat-embed-core-7.0.34.jar) - jar not loaded. See Servlet Spec 2.3, section 9.7.2. Offending class: javax/servlet/Servlet.class
com.jcabi.manifests.ServletMfs: MANIFEST.MF not found in WAR package
com.s3auth.hosts.ScheduledCloudWatch: scheduled for execution with 1 HOURS interval
com.jcabi.manifests.ServletMfs: MANIFEST.MF not found in WAR package
Mar 12, 2015 12:14:55 PM org.apache.coyote.AbstractProtocol start
INFO: Starting ProtocolHandler ["http-bio-53685"]
[INFO]
[INFO] --- exec-maven-plugin:1.3.2:exec (casperjs-test) @ s3auth-rest ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] s3auth ............................................ SUCCESS [6.103s]
[INFO] s3auth-hosts ...................................... SUCCESS [43.150s]
[INFO] s3auth-relay ...................................... SUCCESS [12.340s]
[INFO] s3auth-rest ....................................... FAILURE [1:17.282s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.3.2:exec (casperjs-test) on project s3auth-rest: Command execution failed. Process exited with an error: -2146232576 (Exit value: -2146232576) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :s3auth-rest
[INFO] #stop(53684): in 333Ás
ERROR: IllegalAccessException for stop method in class org.apache.tomcat.maven.plugin.tomcat7.run.ExtendedTomcat
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.tomcat.maven.common.run.EmbeddedRegistry.shutdownAll(EmbeddedRegistry.java:110)
        at org.apache.tomcat.maven.common.run.EmbeddedRegistry$1.run(EmbeddedRegistry.java:69)
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardServer[-1]]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:236)
        at org.apache.catalina.startup.Tomcat.stop(Tomcat.java:351)
        ... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardService[Tomcat]]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:236)
        at org.apache.catalina.core.StandardServer.stopInternal(StandardServer.java:753)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
        ... 7 more
Caused by: org.apache.catalina.LifecycleException: Failed to stop component [StandardEngine[Tomcat]]
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:236)
        at org.apache.catalina.core.StandardService.stopInternal(StandardService.java:502)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
        ... 9 more
Caused by: java.lang.NoClassDefFoundError: org/apache/catalina/core/ContainerBase$StopChild
        at org.apache.catalina.core.ContainerBase.stopInternal(ContainerBase.java:1173)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:232)
        ... 11 more
Caused by: java.lang.ClassNotFoundException: org.apache.catalina.core.ContainerBase$StopChild
        at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
        at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
        ... 13 more
```

**Comment by simonjenga** [comment]
```
[INFO] Reactor Summary:
[INFO]
[INFO] s3auth ............................................ SUCCESS [6.280s]
[INFO] s3auth-hosts ...................................... SUCCESS [46.775s]
[INFO] s3auth-relay ...................................... SUCCESS [23.974s]
[INFO] s3auth-rest ....................................... SUCCESS [14.871s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```
