### ISSUE TITLE
URISyntaxException in HttpRequest ctor

### ISSUE THREAD

**Issue by yegor256** [yegor256/s3auth#275]
```
java.lang.IllegalArgumentException   
  at java.net.URI.create(URI.java:859)  
  at com.s3auth.relay.HttpRequest.<init>(HttpRequest.java:171)  
  at com.s3auth.relay.HttpThread.dispatch(HttpThread.java:151)  
  at com.s3auth.relay.HttpFacade$HttpThreadRunnable.run(HttpFacade.java:259)  
  at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:201)  
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)  
  at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)   
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)   
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:165)  
  at java.util.concurrent.ScheduledThreadPoolExecutor$Sche:  267)  
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)  
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)  
  at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:223)   
  at java.lang.Thread.run(Thread.java:701) 
Caused by: java.net.URISyntaxException: Illegal character in path at index 14: /%7B%7B%20item['social-image']%20%7D%7D   
  at java.net.URI$Parser.fail(URI.java:2825)  
  at java.net.URI$Parser.checkChars(URI.java:2998)  
  at java.net.URI$Parser.parseHierarchical(URI.java:3082)   
  at java.net.URI$Parser.parse(URI.java:3040)   
  at java.net.URI.<init>(URI.java:595)  
  at java.net.URI.create(URI.java:857)  
  ... 13 more 
```

**Comment by yegor256** [comment]
@rultor deploy
