### ISSUE TITLE
runtime Exception

### ISSUE THREAD

**Issue by tomeralmog** [yegor256/s3auth#300]
Hi,
I have followed all the steps, after I input my user and password I get this error:

```
java.io.IOException: failed to fetch / from 'mysite.com' (key=MYKEY): ["'+suffix': Status Code: 403, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: null, AWS Error Message: null", "'+suffix': Status Code: 403, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: null, AWS Error Message: null"]
	at com.s3auth.hosts.DefaultHost.fetch_aroundBody2(DefaultHost.java:228)
	at com.s3auth.hosts.DefaultHost$AjcClosure3.run(DefaultHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:200)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:156)
	at com.s3auth.hosts.DefaultHost.fetch_aroundBody4(DefaultHost.java:166)
	at com.s3auth.hosts.DefaultHost$AjcClosure5.run(DefaultHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:126)
	at com.s3auth.hosts.DefaultHost.fetch(DefaultHost.java:166)
	at com.s3auth.hosts.SmartHost.fetch_aroundBody6(SmartHost.java:115)
	at com.s3auth.hosts.SmartHost$AjcClosure7.run(SmartHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:200)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:156)
	at com.s3auth.hosts.SmartHost.fetch_aroundBody8(SmartHost.java:100)
	at com.s3auth.hosts.SmartHost$AjcClosure9.run(SmartHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:126)
	at com.s3auth.hosts.SmartHost.fetch(SmartHost.java:100)
	at com.s3auth.relay.SecuredHost.secured(SecuredHost.java:199)
	at com.s3auth.relay.SecuredHost.fetch_aroundBody0(SecuredHost.java:103)
	at com.s3auth.relay.SecuredHost$AjcClosure1.run(SecuredHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:200)
	at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
	at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:156)
	at com.s3auth.relay.SecuredHost.fetch_aroundBody2(SecuredHost.java:102)
	at com.s3auth.relay.SecuredHost$AjcClosure3.run(SecuredHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:126)
	at com.s3auth.relay.SecuredHost.fetch(SecuredHost.java:102)
	at com.s3auth.relay.HttpThread.resource(HttpThread.java:247)
	at com.s3auth.relay.HttpThread.dispatch(HttpThread.java:169)
	at com.s3auth.relay.HttpFacade$HttpThreadRunnable.run(HttpFacade.java:261)
	at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:201)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:165)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:223)
	at java.lang.Thread.run(Thread.java:701)
```

**Comment by yegor256** [comment]
@tomeralmog maybe you don't have `index.html` in there?

**Comment by tomeralmog** [comment]
I do, but it is private (I made all the html private - was that wrong?)

**Comment by yegor256** [comment]
@tomeralmog it's not a problem, you can keep them private, but make sure your IAM user has enough permissions to read them.

**Comment by tomeralmog** [comment]
I copied the permissions given in the documentation. is there anything else I have to add?

**Comment by tomeralmog** [comment]
{
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:GetBucketWebsite"
            ],
            "Resource": [
                "arn:aws:s3:::mysite.com/*"
            ]
        }
    ]
}

**Comment by yegor256** [comment]
@tomeralmog maybe making your files "private" overwrite the permissions give by the IAM policy... I think that's how it works

**Comment by tomeralmog** [comment]
when I set it to public, it doesn't authenticate at all

**Comment by tomeralmog** [comment]
Sorry, I am wrong.
It needs to be public. my browser saved the authentication info. when I try it with a different browser it works fine.

**Comment by yegor256** [comment]
@tomeralmog glad it works now. please close the ticket
