### ISSUE TITLE
Test HttpFacadeTest.getsContentOverSSL ends with failure after removing @Ignore annotation

### ISSUE THREAD

**Issue by prondzyn** [yegor256/s3auth#313]
Test [HttpFacadeTest.getsContentOverSSL](https://github.com/yegor256/s3auth/blob/master/s3auth-relay/src/test/java/com/s3auth/relay/HttpFacadeTest.java#L528-L577) ends with failure after removing `@Ignore` annotation but according to PR #194 it should ends with success. 

It is blocking work on the [jcabi-ssl-maven-plugin/issues/2](https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/2).

Below is the test execution listing.

```
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 347.017 sec <<< FAILURE! - in com.s3auth.relay.HttpFacadeTest
getsContentOverSSL(com.s3auth.relay.HttpFacadeTest)  Time elapsed: 31.156 sec  <<< FAILURE!
java.lang.AssertionError: HTTP response body content is not valid:
200 OK [https://localhost:61301/a]
Age: 0
Date: Pt, 16 pa?? 2015 08:20:58 +0200
X-S3auth-Time: 128
Server: relay.s3auth.com, 1.0-SNAPSHOT/123 built on 22-Aug-2012

<<empty>>
Expected: is "secured"
     but: was ""
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.jcabi.http.response.RestResponse.assertBody(RestResponse.java:158)
        at com.s3auth.relay.HttpFacadeTest.getsContentOverSSL(HttpFacadeTest.java:555)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by yegor256** [comment]
@prondzyn brrr... I don't understand. First, what exactly is a bug? What is broken? And my second question, how this project can block jcabi-ssl-maven-plugin? I'm lost :)

**Comment by prondzyn** [comment]
@yegor256 please check the [jcabi/jcabi-ssl-maven-plugin/issues/2](https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/2). It was describing that jcabi-ssl-maven-plugin does not work when Rultor or Travis builts s3auth project. I was trying to reproduce this issue or on my machine and tried to build s3auth with the `@Ignore` removed from `HttpFacadeTest.getsContentOverSSL`. But the test failures with totally different message than is described in [jcabi/jcabi-ssl-maven-plugin/issues/2](https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/2). In [yegor256/s3auth/pull/194](https://github.com/yegor256/s3auth/pull/194) @carlosmiranda described that this test work on his machine without any problems, but it was in July 2014 so I assumed something was broken in the meantime and that's why I created this issue.

**Comment by yegor256** [comment]
@prondzyn but we can't remove `@Ignore` from the test here, until jcabi-ssl-maven-plugin is fixed.. right? It looks like a two way dependency?

**Comment by prondzyn** [comment]
@yegor256 not exactly. First we need to pass the test at local environment because it fails with different reason than @carlosmiranda reported. Then we can commit again with `@Ignore` annotation to work on [jcabi/jcabi-ssl-maven-plugin/issues/2](https://github.com/jcabi/jcabi-ssl-maven-plugin/issues/2). Please, correct me if I stray.

**Comment by yegor256** [comment]
@prondzyn in this case, we can't define "done" in this ticket. If I would be an implementor here, I would ask: you guys just want me to remove `@Ignore`, make sure it fails (but it already fails), put back `@Ignore` and commit? Sounds strange, right? What exactly should be ask ticket implementor to commit (!). Not what to do, but what to commit. Ideas?

**Comment by prondzyn** [comment]
@yegor256 the only thing I can think is "make two commits":  "1. commit test which passes on your local environment" and then "2. commit test with `@Ignore` annotation".

**Comment by yegor256** [comment]
@prondzyn well... how would a code reviewer check that? did it really pass on your local environment or you're lying? that's not a good idea. can't we just ask to remove the `@Ignore` entirely? or maybe introduce a new test?

**Comment by prondzyn** [comment]
@yegor256 both options sounds good. Removing `@Ignore` entirely even better. I noticed that there is a puzzle for this in [HttpFacadeTest.java#L523-L526](https://github.com/yegor256/s3auth/blob/master/s3auth-relay/src/test/java/com/s3auth/relay/HttpFacadeTest.java#L523-L526). I found issue for this #290. So I'm closing this ticket now and will be linking to #290.
