### ISSUE TITLE
NullPointerException thrown out of HttpResponse#send_aroundBody

### ISSUE THREAD

**Issue by simonjenga** [yegor256/s3auth#314]
The following `stack trace` contains several exceptions `java.lang.IllegalStateException` , `java.net.SocketException` , `java.lang.NullPointerException` which happen as the Project Builds.

```
[?[0;37mINFO?[m] 24.245 back-54 com.s3auth.relay.HttpThread: #run(): failure sent to Socket[addr=/127.0.0.1,port=57814,localport=57739]
[?[0;31mERROR?[m] 24.255 back-52 com.s3auth.relay.SecuredHost: #fetch(/a?rnd=QyJBZ, ENTIRE, com.s3auth.hosts.Version$1@3293ae): thrown java.lang.IllegalStateException(hello, world!) out of com.s3auth.relay.HttpFacadeTest$1#answer[95] in 1s
[?[0;31mERROR?[m] 24.255 back-51 com.s3auth.relay.SecuredHost: #fetch(/a?rnd=AfPEA, ENTIRE, com.s3auth.hosts.Version$1@3293ae): thrown java.lang.IllegalStateException(hello, world!) out of com.s3auth.relay.HttpFacadeTest$1#answer[95] in 1s
[?[0;37mINFO?[m] 24.255 back-52 com.s3auth.relay.HttpThread: #dispatch(): java.lang.IllegalStateException: hello, world!
        at com.s3auth.relay.HttpFacadeTest$1.answer(HttpFacadeTest.java:95)
        at com.s3auth.relay.HttpFacadeTest$1.answer(HttpFacadeTest.java:90)
        at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
       [?[0;37mINFO?[m] 24.255 back-51 com.s3auth.relay.HttpThread: #dispatch(): java.lang.IllegalStateException: hello, world!
        at com.s3auth.relay.HttpFacadeTest$1.answer(HttpFacadeTest.java:95)
        at com.s3auth.relay.HttpFacadeTest$1.answer(HttpFacadeTest.java:90)
        at org.mockito.internal.stubbing.StubbedInvocationMatcher.answer(StubbedInvocationMatcher.java:34)
        at org.mockito.internal.handler.MockHandlerImpl.handle(MockHandlerImpl.java:91)
        at org.mockito.internal.handler.NullResultGuardian.handle(NullResultGuardian.java:29)
        at org.mockito.internal.handler.InvocationNotifierHandler.handle(InvocationNotifierHandler.java:38)
        at org.mockito.internal.creation.MethodInterceptorFilter.intercept(MethodInterceptorFilter.java:61)
        at com.s3auth.hosts.Host$$EnhancerByMockitoWithCGLIB$$497c2365.fetch(<generated>)
        at com.s3auth.relay.SecuredHost.fetch_aroundBody0(SecuredHost.java:105)
        at com.s3auth.relay.SecuredHost$AjcClosure1.run(SecuredHost.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
        at com.s3auth.relay.SecuredHost.fetch_aroundBody2(SecuredHost.java:102)
        at com.s3auth.relay.SecuredHost$AjcClosure3.run(SecuredHost.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
        at com.s3auth.relay.SecuredHost.fetch(SecuredHost.java:102)
        at com.s3auth.relay.HttpThread.resource(HttpThread.java:247)
        at com.s3auth.relay.HttpThread.dispatch(HttpThread.java:169)
        at com.s3auth.relay.HttpFacade$HttpThreadRunnable.run(HttpFacade.java:261)
        at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
        at java.lang.Thread.run(Thread.java:745)
[?[0;33mWARN?[m] 54.286 back-91 com.s3auth.relay.HttpFacade$HttpThreadRunnable: java.lang.InterruptedException
[?[0;37mINFO?[m] 54.306 pool-1-thread-15 com.s3auth.relay.HttpFacade: #shutdown(): shutdownNow() succeeded
[?[2;37mDEBUG?[m] 54.316 pool-1-thread-15 com.s3auth.relay.HttpFacade: #close(): in 30.06s
[?[0;33mWARN?[m] 54.316 front-1 com.jcabi.log.VerboseRunnable: escalated exception: java.lang.IllegalStateException: java.net.SocketException: socket closed
        at com.s3auth.relay.HttpFacade.process(HttpFacade.java:188)
        at com.s3auth.relay.HttpFacade.access$100(HttpFacade.java:75)
        at com.s3auth.relay.HttpFacade$1.run(HttpFacade.java:148)
        at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: socket closed
        at java.net.DualStackPlainSocketImpl.accept0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at com.s3auth.relay.HttpFacade.process(HttpFacade.java:186)
        ... 11 more

[?[2;37mDEBUG?[m] 22.695 back-100 com.s3auth.relay.HttpResponse: #withStatus(200): 200 in 11.55-Ás
[?[2;37mDEBUG?[m] 22.695 back-100 com.s3auth.relay.HttpResponse: #withBody(com.s3auth.hosts.ResourceMocker$MkResource$$EnhancerByMockitoWithCGLIB$$a69a4362@1123d8b): 200 in 866.54-Ás
[?[0;31mERROR?[m] 22.695 back-100 com.s3auth.relay.HttpResponse: #send(Socket[addr=/127.0.0.1,port=57760,localport=57753]): thrown java.lang.NullPointerException out of com.s3auth.relay.HttpResponse#send_aroundBody8[181] in 2ms
[?[0;37mINFO?[m] 22.695 back-100 com.s3auth.relay.HttpThread: #dispatch(): java.lang.NullPointerException
        at com.s3auth.relay.HttpResponse.send_aroundBody8(HttpResponse.java:181)
        at com.s3auth.relay.HttpResponse$AjcClosure9.run(HttpResponse.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
        at com.s3auth.relay.HttpResponse.send_aroundBody10(HttpResponse.java:161)
        at com.s3auth.relay.HttpResponse$AjcClosure11.run(HttpResponse.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
        at com.s3auth.relay.HttpResponse.send(HttpResponse.java:161)
        at com.s3auth.relay.HttpThread.dispatch(HttpThread.java:187)
        at com.s3auth.relay.HttpFacade$HttpThreadRunnable.run(HttpFacade.java:261)
        at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
        at java.lang.Thread.run(Thread.java:745)

[?[2;37mDEBUG?[m] 22.695 back-100 com.s3auth.relay.HttpResponse: #withStatus(500): 500 in 17.32-Ás
\n'): 500 in 210.19-Ásre..1691..t java.lang.Thread.run(Thread.java:745)ody('java.lang.NullPointerException
[?[2;37mDEBUG?[m] 22.695 back-100 com.s3auth.relay.HttpResponse: #withHeader('Content-Type', 'text/plain'): 500 in 90.08-Ás
[?[2;37mDEBUG?[m] 22.695 back-100 com.s3auth.relay.HttpException: #response(): 500 in 12.70-Ás
[?[0;33mWARN?[m] 22.695 back-100 com.jcabi.log.VerboseRunnable: swallowed exception: java.lang.IllegalStateException: java.net.SocketException: Socket is closed
        at com.s3auth.relay.HttpThread.failure(HttpThread.java:337)
        at com.s3auth.relay.HttpThread.dispatch(HttpThread.java:214)
        at com.s3auth.relay.HttpFacade$HttpThreadRunnable.run(HttpFacade.java:261)
        at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Socket is closed
        at java.net.Socket.getOutputStream(Socket.java:916)
        at com.s3auth.relay.HttpResponse.send_aroundBody8(HttpResponse.java:161)
        at com.s3auth.relay.HttpResponse$AjcClosure9.run(HttpResponse.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
        at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
        at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
        at com.s3auth.relay.HttpResponse.send_aroundBody10(HttpResponse.java:161)
        at com.s3auth.relay.HttpResponse$AjcClosure11.run(HttpResponse.java:1)
        at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
        at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
        at com.s3auth.relay.HttpResponse.send(HttpResponse.java:161)
        at com.s3auth.relay.HttpThread.failure(HttpThread.java:333)
        ... 11 more

[?[0;33mWARN?[m] 35.710 pool-1-thread-8 com.s3auth.relay.HttpFacade: #shutdown(): failed
[?[0;31mERROR?[m] 45.720 pool-1-thread-8 com.s3auth.relay.HttpFacade: #shutdown(): failed to stop threads
[?[0;33mWARN?[m] 55.729 pool-1-thread-8 com.s3auth.relay.HttpFacade: #shutdown(): failed
[?[0;33mWARN?[m] 55.729 back-31 com.s3auth.relay.HttpFacade$HttpThreadRunnable: java.lang.InterruptedException
[?[0;37mINFO?[m] 55.749 pool-1-thread-8 com.s3auth.relay.HttpFacade: #shutdown(): shutdownNow() succeeded
[?[2;37mDEBUG?[m] 55.759 pool-1-thread-8 com.s3auth.relay.HttpFacade: #close(): in 30.06s
[?[0;33mWARN?[m] 55.759 front-1 com.jcabi.log.VerboseRunnable: escalated exception: java.lang.IllegalStateException: java.net.SocketException: socket closed
        at com.s3auth.relay.HttpFacade.process(HttpFacade.java:188)
        at com.s3auth.relay.HttpFacade.access$100(HttpFacade.java:75)
        at com.s3auth.relay.HttpFacade$1.run(HttpFacade.java:148)
        at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: socket closed
        at java.net.DualStackPlainSocketImpl.accept0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at com.s3auth.relay.HttpFacade.process(HttpFacade.java:186)
        ... 11 more

[?[2;37mDEBUG?[m] 22.558 pool-1-thread-12 com.s3auth.relay.HttpFacade: #listen(): in 588.99-Ás
[?[0;37mINFO?[m] 52.804 pool-1-thread-12 com.s3auth.relay.HttpFacade: #shutdown(): shutdownNow() succeeded
[?[0;33mWARN?[m] 52.814 front-1 com.jcabi.log.VerboseRunnable: escalated exception: java.lang.IllegalStateException: java.net.SocketException: socket closed
        at com.s3auth.relay.HttpFacade.process(HttpFacade.java:188)
        at com.s3auth.relay.HttpFacade.access$100(HttpFacade.java:75)
        at com.s3auth.relay.HttpFacade$1.run(HttpFacade.java:148)
        at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: socket closed
        at java.net.DualStackPlainSocketImpl.accept0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:131)
        at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:398)
        at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
        at java.net.ServerSocket.implAccept(ServerSocket.java:530)
        at java.net.ServerSocket.accept(ServerSocket.java:498)
        at com.s3auth.relay.HttpFacade.process(HttpFacade.java:186)
        ... 11 more

[?[2;37mDEBUG?[m] 52.804 pool-1-thread-12 com.s3auth.relay.HttpFacade: #close(): in 30.06s
Tests run: 11, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 326.067 sec - in com.s3auth.relay.HttpFacadeTest
Running com.s3auth.relay.HttpResponseTest
```

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@simonjenga what I should do to reproduce this? The build is clean on Travis and on my machine (just checked).

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] s3auth ............................................. SUCCESS [  5.824 s]
[INFO] s3auth-hosts ....................................... SUCCESS [ 31.054 s]
[INFO] s3auth-relay ....................................... SUCCESS [ 57.106 s]
[INFO] s3auth-rest ........................................ SUCCESS [ 13.026 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:47 min
[INFO] Finished at: 2015-10-26T09:58:11-07:00
[INFO] Final Memory: 87M/801M
[INFO] ------------------------------------------------------------------------
```

**Comment by simonjenga** [comment]
@yegor256 You are only looking at the final results, please take a look at the full build log.
It is also ```BUILD SUCCESS``` in my machine but there are some problems/exceptions as the build goes on.

```./s3auth/s3auth-relay>mvn clean install```

Take a look at lines 50 -> 80

https://gist.github.com/simonjenga/044f00c4d6165d90970e

**Comment by yegor256** [comment]
@simonjenga than you have to be more specific about why they happen and why do you think they should not be there. At the moment the problem is not reproducible.

**Comment by simonjenga** [comment]
@yegor256 Am sorry, i don't understand you.

I think i have submitted to you everything that you need including details of the problem. It seems to me that submitting defects/bug reports became complex and i am yet to update myself on it.

Does this mean that if you can't reproduce the defect/bug it doesn't exist?

**Comment by yegor256** [comment]
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
