### ISSUE TITLE
The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

### ISSUE THREAD

**Issue by strikeout** [yegor256/s3auth#320]
Hi,

first of all: great Service!

I have a problem getting it up and running tho, 
created cname, bucket, attached policy to user and all. when I'm trying to access the hosted .htpasswd I get the following stack-trace/error:

````
java.io.IOException: failed to fetch /.htpasswd from 'xxx' (key=xx): ["'.htpasswd': Status Code: 400, AWS Service: Amazon S3, AWS Request ID: 0942CB928BEB2F0B, 
AWS Error Code: InvalidRequest, AWS Error Message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.", "'.htpasswd': Status Code: 400, 
AWS Service: Amazon S3, AWS Request ID: 8B560C64FE0E15D5, 
AWS Error Code: InvalidRequest, AWS Error Message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.", "'.htpasswd+suffix': Status Code: 400, AWS Service: Amazon S3, 
AWS Request ID: F11B4CD5D01D219B, AWS Error Code: InvalidRequest, AWS Error Message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.", "'.htpasswd+suffix': Status Code: 400, AWS Service: Amazon S3, AWS Request ID: 8F43631AAF9421D2, AWS Error Code: InvalidRequest, AWS Error Message: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256."]
	at com.s3auth.hosts.DefaultHost.fetch_aroundBody2(DefaultHost.java:228)
	at com.s3auth.hosts.DefaultHost$AjcClosure3.run(DefaultHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
`````

Help would be much appreciated :)

**Comment by strikeout** [comment]
This might be interesting: http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

**Comment by yegor256** [comment]
@strikeout where is your bucket, in which region?

**Comment by strikeout** [comment]
bucket is in frankfurt (eu-west) region

**Comment by yegor256** [comment]
@strikeout we had something like this before: https://github.com/yegor256/s3auth/issues/214 does it help?

**Comment by strikeout** [comment]
Setting the s3 endpoint for frankfurt region to ´´´s3-eu-central-1```` fixed my problem. Thanks for the heads up!

**Comment by markus-hinsche** [comment]
Changing the `~/.boto file` like descriped here https://stackoverflow.com/questions/47929964/gsutil-cannot-copy-to-s3-due-to-authentication?rq=1 helped in our case
