### ISSUE TITLE
large files: broken pipe

### ISSUE THREAD

**Issue by yegor256** [yegor256/s3auth#33]
```
[ERROR] back-8 com.s3auth.relay.HttpResponse: #send('Socket[addr=/85.200.xx.xx,port=40605,localport=80]'): thrown java.net.SocketException ('Broken pipe') in 120ms
[WARN] back-8 com.s3auth.relay.HttpThread: #run(): IO problem: Broken pipe
[ERROR] back-8 com.s3auth.relay.HttpResponse: #send('Socket[addr=/85.200.xx.xx,port=40605,localport=80]'): thrown java.net.SocketException ('Broken pipe') in 190mcs
[ERROR] back-8 com.s3auth.relay.HttpThread: #run(): thrown java.lang.IllegalStateException ('java.net.SocketException: Broken pipe') in 8s
[WARN] back-8 com.jcabi.log.VerboseRunnable: escalated exception: java.lang.IllegalStateException: java.net.SocketException: Broken pipe
    at com.s3auth.relay.HttpThread.failure(HttpThread.java:224)
    at com.s3auth.relay.HttpThread.run_aroundBody0(HttpThread.java:139)
    at com.s3auth.relay.HttpThread$AjcClosure1.run(HttpThread.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:70)
    at com.s3auth.relay.HttpThread.run(HttpThread.java:101)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:143)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
    at java.util.concurrent.ThreadPoolExecutor$Wor:603)
    at com.jcabi.log.VerboseThreads$2.run(VerboseThreads.java:181)
    at java.lang.Thread.run(Thread.java:679)
Caused by: java.net.SocketException: Broken pipe
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:220)
    at sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:290)
    at sun.nio.cs.StreamEncoderimplFlush(StreamEncoder.java:294)
    at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:140)
    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229)
    at com.s3auth.relay.HttpResponse.send_aroundBody0(HttpResponse.java:169)
    at com.s3auth.relay.HttpResponse$AjcClosure1.run(HttpResponse.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:70)
    at com.s3auth.relay.HttpResponse.send(HttpResponse.java:142)
    at com.s3auth.relay.HttpThread.failure(HttpThread.java:222)... 15 more
```

<hr id='w'>

 - `33-9ff485f7`/#95 (by )

**Comment by davvd** [comment]
@yegor256 the last puzzle `33-9ff485f7`/#95 solved
