### ISSUE TITLE
s3auth response timeout and load failure every ~90m

### ISSUE THREAD

**Issue by dhezl** [yegor256/s3auth#330]
Every 90-120m, s3auth hangs when requesting the s3 bucket. Site will freeze (loading) for ~2m and then generate the following error:

```

java.io.IOException: failed to fetch <subdirectory and page> from '<url.com>' (key=<KEY>): ["'<subdirectory and page>': Status Code: 404, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: null, AWS Error Message: null", "'<subdirectory and page>': Status Code: 404, AWS Service: Amazon S3, AWS Request ID: null, AWS Error Code: null, AWS Error Message: null"]
    at com.s3auth.hosts.DefaultHost.fetch_aroundBody2(DefaultHost.java:228)
    at com.s3auth.hosts.DefaultHost$AjcClosure3.run(DefaultHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:200)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:156)
    at com.s3auth.hosts.DefaultHost.fetch_aroundBody4(DefaultHost.java:166)
    at com.s3auth.hosts.DefaultHost$AjcClosure5.run(DefaultHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:126)
    at com.s3auth.hosts.DefaultHost.fetch(DefaultHost.java:166)
    at com.s3auth.hosts.SmartHost.fetch_aroundBody6(SmartHost.java:115)
    at com.s3auth.hosts.SmartHost$AjcClosure7.run(SmartHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:200)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:156)
    at com.s3auth.hosts.SmartHost.fetch_aroundBody8(SmartHost.java:100)
    at com.s3auth.hosts.SmartHost$AjcClosure9.run(SmartHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:126)
   at com.s3auth.hosts.SmartHost.fetch(SmartHost.java:100)
    at com.s3auth.relay.SecuredHost.secured(SecuredHost.java:199)
    at com.s3auth.relay.SecuredHost.fetch_aroundBody0(SecuredHost.java:103)
    at com.s3auth.relay.SecuredHost$AjcClosure1.run(SecuredHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:200)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:156)
    at com.s3auth.relay.SecuredHost.fetch_aroundBody2(SecuredHost.java:102)
    at com.s3auth.relay.SecuredHost$AjcClosure3.run(SecuredHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:126)
    at com.s3auth.relay.SecuredHost.fetch(SecuredHost.java:102)
    at com.s3auth.relay.HttpThread.resource(HttpThread.java:247)
    at com.s3auth.relay.HttpThread.dispatch(HttpThread.java:169)
    at com.s3auth.relay.HttpFacade$HttpThreadRunnable.run(HttpFacade.java:261)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:201)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:223)
    at java.lang.Thread.run(Thread.java:701)
```

Site eventually resumes operation. For reference, we are using s3auth at the bucket level, with multiple staging sites residing within various subdirectories.

**Comment by davvd** [comment]
@yegor256 dispatch this issue please, see [par.21](http://at.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@dhezlrazorfish hm... that's strange. are you sure you're requesting an object that exists in S3?

**Comment by dhezlrazorfish** [comment]
We are -- there are `index.html` files both at the root level, and in each relevant project path.

90% of the time, s3auth works swimmingly.

If it is any help, we have `.htaccess` and `.htpasswd` files at root as well, though they don't seem to be causing any issue.

**Comment by yegor256** [comment]
This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order
