### ISSUE TITLE
java.lang.IllegalStateException raised spuriously.

### ISSUE THREAD

**Issue by bigdelys** [yegor256/s3auth#335]
We are seeing java.lang.IllegalStateException every once in a while, sometimes it stays for a few seconds, and after multiple refreshes:
`
java.lang.IllegalStateException: thread 'back-39' in group 'back' interrupted
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:182)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.s3auth.hosts.DefaultBucket.bucket(DefaultBucket.java:112)
    at com.s3auth.hosts.DefaultHost.fetch_aroundBody2(DefaultHost.java:178)
    at com.s3auth.hosts.DefaultHost$AjcClosure3.run(DefaultHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
    at com.s3auth.hosts.DefaultHost.fetch_aroundBody4(DefaultHost.java:168)
    at com.s3auth.hosts.DefaultHost$AjcClosure5.run(DefaultHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
    at com.s3auth.hosts.DefaultHost.fetch_aroundBody6(DefaultHost.java:168)
    at com.s3auth.hosts.DefaultHost$AjcClosure7.run(DefaultHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
    at com.s3auth.hosts.DefaultHost.fetch(DefaultHost.java:168)
    at com.s3auth.hosts.SmartHost.fetch_aroundBody6(SmartHost.java:119)
    at com.s3auth.hosts.SmartHost$AjcClosure7.run(SmartHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
    at com.s3auth.hosts.SmartHost.fetch_aroundBody8(SmartHost.java:104)
    at com.s3auth.hosts.SmartHost$AjcClosure9.run(SmartHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
    at com.s3auth.hosts.SmartHost.fetch_aroundBody10(SmartHost.java:104)
    at com.s3auth.hosts.SmartHost$AjcClosure11.run(SmartHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
    at com.s3auth.hosts.SmartHost.fetch(SmartHost.java:104)
    at com.s3auth.hosts.FastHost.fetch_aroundBody0(FastHost.java:90)
    at com.s3auth.hosts.FastHost$AjcClosure1.run(FastHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodInterrupter.wrap(MethodInterrupter.java:115)
    at com.s3auth.hosts.FastHost.fetch(FastHost.java:90)
    at com.s3auth.hosts.RejectingHost.fetch(RejectingHost.java:108)
    at com.s3auth.relay.SecuredHost.secured(SecuredHost.java:199)
    at com.s3auth.relay.SecuredHost.fetch_aroundBody0(SecuredHost.java:103)
    at com.s3auth.relay.SecuredHost$AjcClosure1.run(SecuredHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapMethod(MethodLogger.java:164)
    at com.s3auth.relay.SecuredHost.fetch_aroundBody2(SecuredHost.java:102)
    at com.s3auth.relay.SecuredHost$AjcClosure3.run(SecuredHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:134)
    at com.s3auth.relay.SecuredHost.fetch(SecuredHost.java:102)
    at com.s3auth.relay.HttpThread.resource(HttpThread.java:247)
    at com.s3auth.relay.HttpThread.dispatch(HttpThread.java:169)
    at com.s3auth.relay.HttpFacade$HttpThreadRunnable.run(HttpFacade.java:264)
    at com.jcabi.log.VerboseRunnable.run(VerboseRunnable.java:198)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask$Sync.innerRunAndReset(FutureTask.java:351)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:178)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:165)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1146)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at com.jcabi.log.VerboseThreads$Wrap.run(VerboseThreads.java:220)
    at java.lang.Thread.run(Thread.java:701)
`

**Comment by yegor256** [comment]
@bigdelys I'll fix it now

**Comment by yegor256** [comment]
@rultor deploy

**Comment by yegor256** [comment]
@rultor try to deploy

**Comment by yegor256** [comment]
@bigdelys should be fine now, please check

**Comment by bigdelys** [comment]
Thank you very much. It seems to be fixed.

- Nima

**Comment by zaharidichev** [comment]
Well.... It does not seem that resolved after all. 

```java
java.lang.IllegalStateException: thread 'back-58' in group 'back' interrupted
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:182)
    at com.jcabi.aspects.aj.MethodLogger.ajc$inlineAccessMethod$com_jcabi_aspects_aj_MethodLogger$com_jcabi_aspects_aj_MethodLogger$wrap(MethodLogger.java:1)
    at com.jcabi.aspects.aj.MethodLogger.wrapClass(MethodLogger.java:136)
    at com.s3auth.hosts.DefaultBucket.name(DefaultBucket.java:94)
    at com.s3auth.hosts.DefaultHost.fetch_aroundBody2(DefaultHost.java:228)
    at com.s3auth.hosts.DefaultHost$AjcClosure3.run(DefaultHost.java:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
```

Can we request some urgency here as we relied on that particular service and that brings us quite a bit  of problems at this very moment.

**Comment by lukesaunders** [comment]
I have this same issue. Using the hosted s3auth.com service, sometimes requests for files work fine, and other times I get a 500. The stacktrace given is https://gist.github.com/lukesaunders/3b28da26a8e0036c01d7e9c0abb4fc63

Strangely, of the two domains I've set up, one works fine and the other has the problem. The only difference seems to be concurrency - one domain loads a few files concurrently (around 4), and the other can load many (around 60). Is there a concurrency limit?

**Comment by lukesaunders** [comment]
@yegor256 could you reopen this issue or shall I create a new one?

**Comment by yegor256** [comment]
We have #348 to continue with this problem
