### ISSUE TITLE
unable to download certain filetypes

### ISSUE THREAD

**Issue by bobweston** [yegor256/s3auth#342]
I'm trying to distribute files to some folks using S3auth. (I own the rights to the files, by the way). If the file is in zip format, it works as expected. But it won't prompt to download doc, docx or excel files.

Is this an expected behavior? Can that be changed?

I love the app and appreciate your feedback.

The error I am seeing is (in part) below:

<pre>
java.io.IOException: failed to fetch /projects/2016/release.docx from 'my.domain.com' (key=XXXXXXXXXXXXXXX): ["'projects/2016/release.docx': Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 707A9D1D2F2E09B4)", "'project/2016/release.docx': Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: XXXXXXXXXXXXXX)", "'projects/2016/release.docx+suffix': Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: XXXXXXXXXXXX)", "'projects/2016/release.docx+suffix': Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: 4CBB8A9289D2401C)"]
	at com.s3auth.hosts.DefaultHost.fetch_aroundBody2(DefaultHost.java:228)
	at com.s3auth.hosts.DefaultHost$AjcClosure3.run(DefaultHost.java:1)
	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
	at com.jcabi.aspects.aj.MethodLogger.wrap(MethodLogger.java:212)
</pre>

**Comment by bobweston** [comment]
I noticed that if I add the user to a group with higher permissions, s3Auth now displays an autogenerated page that makes it seem that s3 auth sees excel files as a directory, not an auth.

This is what I see after clicking on the link to an excel file:

This is page is auto-generated by s3auth.com.

The prefix is: projects/2016/xxxxxxxx.xlsx/
Name 	Size (bytes)

**Comment by davvd** [comment]
@yegor256 please take a look at it and dispatch (see [par.21](http://at.teamed.io/policy.html#21))

**Comment by yegor256** [comment]
@bobweston are you sure that that `.xlsx` file is not a directory technically? It seems that it really is. Can you give me access there?

**Comment by bobweston** [comment]
It most definite;y was not a directory. I uploaded the Excel file myself. I've found an alternative solution to what we were trying to use this for though.

I appreciate your attempting to help.

**Comment by yegor256** [comment]
@bobweston I'm sorry this bug is still not fixed. We didn't have enough funds/time to work on the project. However, recently we received some donations from our grateful users and will continue to fix issues and introduce new features. Would be great if you can also donate -- to help us move forward faster. Here is the link: https://www.0crat.com/contrib/C3RP1J1CH
