### ISSUE TITLE
Getting invalid first line: 'GET http://MY_HOST_HERE/ HTTP/1.1' error

### ISSUE THREAD

**Issue by digitalsanctum** [yegor256/s3auth#364]
I'm using s3auth.com for two sites and both are now resulting in

> invalid first line: 'GET http://MY_HOST_HERE/ HTTP/1.1'

There have been no recent changes to either sites configuration so I believe this issue is caused by s3auth.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by yegor256** [comment]
@digitalsanctum are you getting this in a browser? Can you attach a screenshot pls.

**Comment by digitalsanctum** [comment]
Sure. Here's a screenshot.
![s3-error](https://user-images.githubusercontent.com/30923/29188182-2bc03cfe-7dc7-11e7-8a36-96d82a238dea.png)

**Comment by digitalsanctum** [comment]
After further investigation it seems curl works fine but using Chrome or Safari results in the above so I think this is a proxy issue on my side. Sorry for the false alarm.

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT ${buildNumber} 2017-08-10T18:35:57
IllegalStateException: java.lang.reflect.InvocationTargetException
com.zerocracy.jstk.SoftException: Job `gh:yegor256/s3auth#364` was not in scope
	at com.zerocracy.pm.scope.Wbs.remove(Wbs.java:107)
	at com.zerocracy.pm.scope.Wbs$remove$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at com.zerocracy.stk.pm.scope.wbs.remove_job_from_wbs.exec(remove_job_from_wbs.groovy:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:109)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:90)
	at com.zerocracy.farm.react...
```
